includes:
  - configs/datasets/hateful_memes/with_features.yaml

model_config:
  visual_bert:
    training_head_type: classification
    num_labels: 2
    losses:
      - cross_entropy

dataset_config:
  hateful_memes:
    return_features_info: true
    processors:
      masked_region_processor:
        type: masked_region
        params:
          mask_probability: 0.15
          mask_region_probability: 0.9
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: 22000

evaluation:
  metrics:
    - accuracy
    - binary_f1
    - roc_auc

training:
  batch_size: 16
  lr_scheduler: true
  max_updates: 3000
  find_unused_parameters: true
  early_stop:
    criteria: hateful_memes/roc_auc
    minimize: false
  num_workers: 0

checkpoint:
  pretrained_state_mapping:
    model.bert: model.bert
